2024-09-18 11:34:43,082 ERROR: Exception on /index [GET] [in E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\app\main\routes.py", line 47, in index
    return render_template('index.html', title=_('Home'), form=form,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Thihansa\Bluechip Technologies\microblog\app\templates\index.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\app\templates\base.html", line 59, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\app\templates\index.html", line 10, in block 'content'
    {% include '_post.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\app\templates\_post.html", line 4, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2024-09-18 11:42:35,936 INFO: Microblog startup [in E:\Thihansa\Bluechip Technologies\microblog\app\__init__.py:79]
2024-09-18 11:43:10,537 ERROR: Exception on /auth/login [GET] [in E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\app\auth\routes.py", line 30, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Thihansa\Bluechip Technologies\microblog\app\templates\auth\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\app\templates\base.html", line 59, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\app\templates\auth\login.html", line 25, in block 'content'
    <p>New User? <a href="{{ url_for('main.register') }}">Click to Register!</a></p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Thihansa\Bluechip Technologies\microblog\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.register'. Did you mean 'auth.register' instead?
2024-09-18 11:49:37,062 INFO: Microblog startup [in E:\Thihansa\Bluechip Technologies\microblog\app\__init__.py:79]
2024-09-18 11:57:58,530 INFO: Microblog startup [in E:\Thihansa\Bluechip Technologies\microblog\app\__init__.py:79]
2024-09-18 22:16:58,796 INFO: Microblog startup [in E:\Thihansa\Bluechip Technologies\microblog\app\__init__.py:79]
2024-09-18 23:08:20,639 INFO: Microblog startup [in E:\Thihansa\Bluechip Technologies\microblog\app\__init__.py:81]
2024-09-18 23:11:48,397 INFO: Microblog startup [in E:\Thihansa\Bluechip Technologies\microblog\app\__init__.py:81]
